# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/ml.data.ipynb.

# %% auto 0
__all__ = ['ZippedDataLoader']

# %% ../../nbs/ml.data.ipynb 3
class ZippedDataLoader:
    def __init__(self, *data_loaders):
        self.data_loaders = data_loaders

    def __iter__(self):
        self.it = iter(zip(*self.data_loaders))
        return self

    def __next__(self):
        return next(self.it)
