# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/ml.mcd.ipynb.

# %% auto 0
__all__ = ['discrepancy']

# %% ../../nbs/ml.mcd.ipynb 3
import torch
import torch.nn.functional as F

# %% ../../nbs/ml.mcd.ipynb 4
def discrepancy(a, b):
    return torch.mean(torch.abs(F.softmax(a, dim=-1) - F.softmax(b, dim=-1)))
