# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/testing.ipynb.

# %% auto 0
__all__ = ['FIXTURE_DIRECTORY', 'get_fixture_path']

# %% ../nbs/testing.ipynb 2
from pathlib import Path

FIXTURE_DIRECTORY = Path('./fixtures').resolve()

def get_fixture_path(relative_path):
    return FIXTURE_DIRECTORY / relative_path
