# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/dspy.predict.ccot.ipynb.

# %% auto 0
__all__ = ['log']

# %% ../../../nbs/dspy.predict.ccot.ipynb 3
import dspy
from dspy.primitives.program import Module
from dspy.signatures.signature import ensure_signature

from ...logging import get_logger

log = get_logger(__name__)
