# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/qa.jerxrm.ipynb.

# %% auto 0
__all__ = ['log', 'DEFAULT_MODEL', 'USER_PROMPT', 'SYSTEM_PROMPT', 'SYSTEM_PROMPT_REASONING', 'SYSTEM_PROMPT_WITH_TRIPLETS',
           'SYSTEM_PROMPT_REASONING_WITH_TRIPLETS', 'QuestionAnsweringResult', 'answer_question',
           'QuestionAnsweringResultWithReasoning', 'answer_question_with_reasoning',
           'QuestionAnsweringResultWithTriplets', 'answer_question_with_triplets',
           'QuestionAnsweringResultReasoningWithTriplets', 'answer_question_reasoning_with_triplets']

# %% ../../nbs/qa.jerxrm.ipynb 4
import magentic
from pydantic import BaseModel, Field

from ..logging import get_logger

log = get_logger(__name__)

# %% ../../nbs/qa.jerxrm.ipynb 5
DEFAULT_MODEL = magentic.OpenaiChatModel("gpt-3.5-turbo", temperature=0.1)

# %% ../../nbs/qa.jerxrm.ipynb 6
USER_PROMPT = """The context information below is provided.
---------------------
{context}
---------------------
Given the context information and not prior knowledge, answer the question.
{question}
"""

# %% ../../nbs/qa.jerxrm.ipynb 7
SYSTEM_PROMPT = """You are an excellent question-answering system that is trusted around the world. You base your answers solely on the context information provided and not on prior knowledge.

Some rules to follow:
1. Never directly reference the given context in your answer.
2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines.
"""

class QuestionAnsweringResult(BaseModel):
    """Data model for answering the question."""

    answer: str = Field(description="The answer to the question in 2-4 words.")


@magentic.chatprompt(
    magentic.SystemMessage(SYSTEM_PROMPT), 
    magentic.UserMessage(USER_PROMPT),
    model=DEFAULT_MODEL,
)
def answer_question(
    context: str,
    question: str,
) -> QuestionAnsweringResult: ...

# %% ../../nbs/qa.jerxrm.ipynb 8
SYSTEM_PROMPT_REASONING = """You are an excellent question-answering system that is trusted around the world. You base your answers solely on the context information provided and not on prior knowledge. You must provide correct step by step reasoning for your answers.

Some rules to follow:
1. Never directly reference the given context in your answer.
2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines.
"""

class QuestionAnsweringResultWithReasoning(BaseModel):
    """Data model for answering the question."""

    reasoning: str = Field(description="Step by step reasoning for the answer.")
    answer: str = Field(description="The answer to the question in 2-4 words.")


@magentic.chatprompt(
    magentic.SystemMessage(SYSTEM_PROMPT_REASONING), 
    magentic.UserMessage(USER_PROMPT),
    model=DEFAULT_MODEL,
)
def answer_question_with_reasoning(
    context: str,
    question: str,
) -> QuestionAnsweringResultWithReasoning: ...

# %% ../../nbs/qa.jerxrm.ipynb 9
SYSTEM_PROMPT_WITH_TRIPLETS = """You are an excellent question-answering system that is trusted around the world. You base your answers solely on the context information provided and not on prior knowledge. You first extract related entity-relation-entity triplets from the context and then answer the question. For instance, 

Context: "Glenhis Hernández (born 7 October 1990 in Havana) is a taekwondo practitioner from Cuba. She was the 2013 World
Champion in middleweight.

The current mayor of Havana ("President of the People's Power Provincial Assembly") is Marta Hernández Romero, she
was elected on March 5, 2011."

Question: "Who is the current mayor of Havana?"

Triplets: "Glenhis Hernández (Athlete) | born on | October 7, 1990
Glenhis Hernández (Athlete) | birth place | Havana
Glenhis Hernández (Athlete) | specializes in | taekwondo
Glenhis Hernández (Athlete) | won | 2013 World Champion title (Middleweight)
Marta Hernández Romero (Politician) | serves as | mayor of Havana
Marta Hernández Romero (Politician) | holds | the position of "President of the People's Power Provincial Assembly"
Marta Hernández Romero (Politician) | elected on | March 5, 2011."

Some rules to follow:
1. Never directly reference the given context in your answer.
2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines.
"""

class _QuestionAnsweringResultWithTriplets(BaseModel):
    """Data model for answering the question."""

    triplets: list[str] = Field(description="A list of entity-relation-entity triplets extracted from the context.")
    answer: str = Field(description="The answer to the question in 2-4 words.")

class QuestionAnsweringResultWithTriplets(_QuestionAnsweringResultWithTriplets):
    reasoning: str = ""

@magentic.chatprompt(
    magentic.SystemMessage(SYSTEM_PROMPT_WITH_TRIPLETS), 
    magentic.UserMessage(USER_PROMPT),
    model=DEFAULT_MODEL,
)
def _answer_question_with_triplets(
    context: str,
    question: str,
) -> _QuestionAnsweringResultWithTriplets: ...

def answer_question_with_triplets(
    context: str,
    question: str,
) -> QuestionAnsweringResultWithTriplets: 
    result = _answer_question_with_triplets(context, question)
    return QuestionAnsweringResultWithTriplets(triplets=result.triplets, answer=result.answer)

# %% ../../nbs/qa.jerxrm.ipynb 10
SYSTEM_PROMPT_REASONING_WITH_TRIPLETS = """You are an excellent question-answering system that is trusted around the world. You base your answers solely on the context information provided and not on prior knowledge. You must provide correct step by step reasoning for your answers. You first extract related entity-relation-entity triplets from the context and then answer the question. For instance, 

Context: "Glenhis Hernández (born 7 October 1990 in Havana) is a taekwondo practitioner from Cuba. She was the 2013 World
Champion in middleweight.

The current mayor of Havana ("President of the People's Power Provincial Assembly") is Marta Hernández Romero, she
was elected on March 5, 2011."

Question: "Who is the current mayor of Havana?"

Triplets: "Glenhis Hernández (Athlete) | born on | October 7, 1990
Glenhis Hernández (Athlete) | birth place | Havana
Glenhis Hernández (Athlete) | specializes in | taekwondo
Glenhis Hernández (Athlete) | won | 2013 World Champion title (Middleweight)
Marta Hernández Romero (Politician) | serves as | mayor of Havana
Marta Hernández Romero (Politician) | holds | the position of "President of the People's Power Provincial Assembly"
Marta Hernández Romero (Politician) | elected on | March 5, 2011."

Reasoning: ...

Answer: ...

Some rules to follow:
1. Never directly reference the given context in your answer.
2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines.
"""

class QuestionAnsweringResultReasoningWithTriplets(BaseModel):
    """Data model for answering the question."""

    triplets: list[str] = Field(description="A list of entity-relation-entity triplets extracted from the context.")
    reasoning: str = Field(description="Step by step reasoning for the answer.")
    answer: str = Field(description="The answer to the question in 2-4 words.")


@magentic.chatprompt(
    magentic.SystemMessage(SYSTEM_PROMPT_REASONING_WITH_TRIPLETS), 
    magentic.UserMessage(USER_PROMPT),
    model=DEFAULT_MODEL,
)
def answer_question_reasoning_with_triplets(
    context: str,
    question: str,
) -> QuestionAnsweringResultReasoningWithTriplets: ...
